- script.sh
Update regex to accomodate SED order
Fix include header removal in EN migration
> fix: migration script

- script.sh
captures textblocks referencing other textblocks
captures textblocks across multiple levels
> fix: textblock patterns

- script.sh
updates position to index status
deletes unneeded attributes
refactors global actions
> feat: migrate header attributes

- docs/de-de/modules/plugins/pages/faq-plugins.adoc
- docs/en-gb/modules/plugins/pages/faq-plugins.adoc
Reverts plentymarkets/plenty-manual-docs#522
> Revert "feat: update plugin faq"

- docs/de-de/modules/crm/pages/kontakt-bearbeiten.adoc
- docs/en-gb/modules/crm/pages/edit-contact.adoc
> ADD derive invoice / delivery address function

- .github/workflows/CD.yml
- .github/workflows/CI.yml
- Add way to prevent build
- Remove CI path restraint
> refactor: CI/CD

- .github/workflows/CD.yml
- Retain faster publishing times
> refactor: step order

- .github/workflows/CD.yml
- .github/workflows/health-check.yml
- .htmltest.yml
- Update config
- Shorten CD execution time
- Switch health check runners
> fix: htmltest

- antora-playbook-de.yml
- antora-playbook-en.yml
- lib/caution-to-warning.js
- Automatically converts caution blocks to warning blocks
> feat: create caution block handling

- docs/de-de/modules/webshop/pages/best-practices.adoc
- docs/de-de/modules/webshop/pages/ceres-3-update.adoc
- docs/de-de/modules/webshop/pages/ceres-einrichten.adoc
- docs/de-de/modules/webshop/pages/faq-lts.adoc
- docs/de-de/modules/webshop/pages/feedbacks-verwalten.adoc
- docs/de-de/modules/webshop/pages/io-einrichten.adoc
- docs/de-de/modules/webshop/pages/mandanten-verwalten.adoc
- docs/de-de/modules/webshop/pages/shop-builder.adoc
- docs/de-de/modules/webshop/pages/template-variablen-in-Ceres.adoc
- docs/de-de/modules/webshop/pages/webinar-css.adoc
> ADD: meta descriptions for plentyShop LTS pages pt1

- docs/de-de/modules/business-entscheidungen/pages/artikel-meldebestand-live.adoc
- docs/en-gb/modules/business-decisions/pages/items-reorderlevel-live.adoc
https://dev.azure.com/plentymarkets/plentymarkets/_workitems/edit/38552
> ADD page as requested in Azure

- docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
- docs/en-gb/modules/business-decisions/pages/user-accounts-access.adoc
The directory of the email tab changed within the settings UI. This change is now adapted in the manual
> dennis/change:directory of email tab in BD

- docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
- docs/en-gb/modules/business-decisions/pages/user-accounts-access.adoc
Directory of the Email tab in Settings UI changed. This was updated in the manual
> change:directory of email tab in business decision

- docs/de-de/modules/business-entscheidungen/pages/domains.adoc
I extended the part of generating the Auth-Code with a few lines about necessary steps to be able to generate it in the first place
> added: info about when a user is able to generate an AC

- docs/de-de/modules/ROOT/nav.adoc
- docs/de-de/modules/business-entscheidungen/pages/praxisbeispiel-301-Weiterleitungen.adoc
Added another practical in the system administration about 301 redirects
> add: practical example for 301 redirects

- docs/de-de/modules/ROOT/nav.adoc
- docs/de-de/modules/business-entscheidungen/pages/praxisbeispiel-301-Weiterleitungen.adoc
- docs/de-de/modules/business-entscheidungen/pages/praxisbeispiele.adoc
added two more examples as well as a list with usable icons within a redirect
> added: more 301-redirect examples

- docs/de-de/modules/ROOT/nav.adoc
- docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
- docs/de-de/modules/business-entscheidungen/pages/praxisbeispiel-externes-frontend-plenty-backend.adoc
- docs/en-gb/modules/business-decisions/pages/user-accounts-access.adoc
Changed 3.2 activating owners because owners are now activated by ticking *edit* and *create* in the simple view.
> change:owner rights now in simple view

- docs/de-de/modules/_includes/partials/rights.adoc
- docs/de-de/modules/willkommen/pages/system-personalisieren.adoc
- docs/en-gb/modules/_includes/partials/rights.adoc
- docs/en-gb/modules/business-decisions/pages/user-accounts-access.adoc
- docs/en-gb/modules/welcome/pages/customise-system.adoc
This reverts commit 7973c4b71f5985a70b4de12b0a5625cf8f247029.
> Revert "change: personalise your system, rights iclude (#2060)"

- docs/de-de/modules/_includes/partials/rights.adoc
- docs/de-de/modules/willkommen/pages/system-personalisieren.adoc
- docs/en-gb/modules/_includes/partials/rights.adoc
- docs/en-gb/modules/business-decisions/pages/user-accounts-access.adoc
- docs/en-gb/modules/welcome/pages/customise-system.adoc
Reverts plentymarkets/plenty-manual-docs#2063
> Revert "Revert "change: personalise your system, rights iclude (#2060)""

- docs/de-de/modules/business-entscheidungen/pages/roadmap.adoc
- docs/en-gb/modules/business-decisions/pages/roadmap.adoc
Replaced former roadmap content, as demanded by the responsible party
> Added Roadmap OP 1 2023 DE + EN

- docs/de-de/modules/business-entscheidungen/pages/roadmap.adoc
- docs/en-gb/modules/business-decisions/pages/roadmap.adoc
There's a lot more text in the third columnd this time around. Looked weird as 2,1,1
> change: Column width for roadmap

- docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
- docs/de-de/modules/business-entscheidungen/pages/dns-selbsthilfe.adoc
- docs/de-de/modules/business-entscheidungen/pages/domains.adoc
- docs/de-de/modules/business-entscheidungen/pages/e-mail-postfächer-verwalten.adoc
- docs/de-de/modules/business-entscheidungen/pages/eigene-cloud-infrastruktur.adoc
- docs/de-de/modules/business-entscheidungen/pages/hosting-daten.adoc
- docs/de-de/modules/business-entscheidungen/pages/praxisbeispiel-externes-frontend-plenty-backend.adoc
- docs/de-de/modules/business-entscheidungen/pages/praxisbeispiele.adoc
- docs/de-de/modules/business-entscheidungen/pages/ssl-zertifikat_bestellen.adoc
- docs/de-de/modules/business-entscheidungen/pages/system-umzug.adoc
- docs/de-de/modules/business-entscheidungen/pages/systemadministration.adoc
- docs/de-de/modules/business-entscheidungen/pages/verfahrensdokumentation.adoc
- docs/de-de/modules/business-entscheidungen/pages/versionszyklus.adoc
- docs/de-de/modules/willkommen/pages/login-rundgang.adoc
Replaced plentymarkets with plentysystems and updated menu path on the welcome page
> UPDATE: welcome page and business decision pages

- docs/de-de/modules/business-entscheidungen/pages/zentraler-login.adoc
added a config for creating a plentysystems account and a config for inviting a user while simultaneously creating a user account
> extend central login page

- docs/de-de/modules/business-entscheidungen/pages/zentraler-login.adoc
fixed table name, App Pin include file and material icon
> FIX: Second table on central login page

- docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
- docs/de-de/modules/business-entscheidungen/pages/zentraler-login.adoc
added information about connecting user accounts with plentysystems accounts also added includes
> Updated user accounts page

- docs/en-gb/modules/welcome/pages/login-tour.adoc
changed the path from [...]/assets/[...] to [...]/images/[...]
> Add dennis translation updated welcome page

- docs/de-de/modules/business-entscheidungen/pages/dein-vertrag.adoc
- docs/en-gb/modules/business-decisions/pages/your-contract.adoc
Entry point moved from Start to user account
> fix: my account path

- docs/de-de/modules/maerkte/pages/otto-o-auth.adoc
- docs/en-gb/modules/markets/pages/otto-o-auth.adoc
changed the part "reload the assistant" to "reload the browser tab"
> changed assistant to browser tab

- docs/de-de/modules/business-entscheidungen/pages/roadmap.adoc
- docs/en-gb/modules/business-decisions/pages/roadmap.adoc
- PWA Docs to completed
- PWA MVP2 to completed
- plentyShop settings tree to completed
> feat: update roadmap

- .github/workflows/CD.yml
- .github/workflows/health-check.yml
- .gitignore
- README.adoc
- package-lock.json
- package.json
- Update package.json with correct versions
- Add scripts as shortcuts
- Update GH workflows
> feat: improve setup

- package.json
- Use rsync over cp to support other environments
> fix: postinstall script

- antora-playbook-de.yml
- robots.txt
> allow druidai-kb as user agent

- docs/de-de/modules/maerkte/pages/otto-o-auth.adoc
- docs/en-gb/modules/markets/pages/otto-o-auth.adoc
change otto oauth date from 31st to 30th of paril.
> change otto oauth  date

- docs/de-de/modules/willkommen/pages/system-personalisieren.adoc
- docs/en-gb/modules/welcome/pages/customise-system.adoc
My very last pull request for plenty 💔 🚀 
changed author tag because @asachs-plenty will be in charge of this manual page from now on. Hasta la vista!
> change author tag

- docs/de-de/modules/maerkte/partials/emag-offers-recommended-mappings.adoc
- docs/en-gb/modules/markets/partials/emag-offers-recommended-mappings.adoc
- Added info about complex mapping
- Fixed minor typo
> Add info for emag mapping
